version: '3.9'

services:
  logstash:
    container_name: logstash
    hostname: logstash
    ports:
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx8g -Xms8g"
    build:
      context: ./logstash
    volumes:
      - ${PWD}/logstash/logstash.sh:/root/entrypoint.sh:ro
      - ${PWD}/logstash/files/logstash.yml:/root/config/logstash.yml:ro
      - ${PWD}/logstash/files/pipelines.yml:/root/config/pipelines.yml:ro
      - ${PWD}/logstash/files/pipelines:/root/pipelines:ro
      - ${PWD}/logstash/files/server.log:/root/server.log:ro